data-path="./src/networks/ethash/nodes/node-1/data" 

# Chain
genesis-file="./src/networks/ethash/config/network/genesis.json" 

# Mining
miner-enabled=true 
miner-coinbase="fe3b557e8fb62b89f4916b721be55ceb828dbd73" 

# Network
rpc-http-enabled=true
host-allowlist=["*"]
rpc-http-cors-origins=["all"]